server:
  port: 8010
user:
  userServiceUrl:
    findById: http://localhost:8000/provider-user/
spring:
  application:
    name: consumer-shop
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true