server:
  port: 8010
user:
  userService:
    instance: provider-user
    basicAuth:
      username: admin
      password: admin
spring:
  application:
    name: consumer-shop
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:nimda@peer1:8761/eureka/,http://admin:nimda@peer2:8762/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
feign:
  client:
    config:
      provider-user:
        loggerLevel: basic

logging:
  level:
    com.cris.superplatform.consumer.shop.feign.client.UserFeignClient: DEBUG