server:
  port: 8031
spring:
  application:
    name: turbine-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:nimda@peer1:8761/eureka/,http://admin:nimda@peer2:8762/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
turbine:
  appConfig: consumer-shop,my-consumer-experiment
  clusterNameExpression: "'default'"
  instanceUrlSuffix: /hystrix.stream