server:
  port: 8888
spring:
  application:
    name: provider-user
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:nimda@peer1:8761/eureka/,http://admin:nimda@peer2:8762/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true