spring:
  application:
    name: eureka-server
  security:
    basic:
      enabled: true #开启基于HTTP Basic的认证 spring sercurity4之后废弃该配置了
    user:
      name: admin #配置登入账号
      password: nimda #配置登入密码，不设置会有随机值在启动时在控制台打印出来

---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://admin:nimda@peer2:8762/eureka/
---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://admin:nimda@peer1:8761/eureka/