server:
  port: 8000
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource: #指定数据源
    platform: h2 #指定数据源类型
    schema: classpath:schema.sql #指定h2数据库建表脚本
    data: classpath:data.sql #指定h2数据库数据脚本
  application:
    name: provider-user
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:nimda@peer1:8761/eureka/,http://admin:nimda@peer2:8762/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    metadata-map:
      my-metadata: 测试元数据 #key和value随便填写
logging: #指定日志级别让hibernate打印sql
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE